### ISSUE TITLE
About resize issue

### ISSUE THREAD

**Issue by softwareklinic** [JuanCarniglia/kbn_circles_vis#1]
I was able to make it work with Kibana 4.4.2 - but when i resize the visualization in dashboard - it doesn't shrink or grow -- it has a static size... not responsive.. can u check that

**Comment by JuanCarniglia** [comment]
Yeah.. true... I'll change the size in pxs to % relative to container, as soon as I can.Thanks for the feedback.

**Comment by JuanCarniglia** [comment]
I made some big changes on this visualization, including Panning and Zooming, I think this changes will be useful to you. Please, try it and let me know how it goes.

**Comment by softwareklinic** [comment]
Ty will let you know
