### ISSUE TITLE
npm run build failure

### ISSUE THREAD

**Issue by zuoez02** [JuanCarniglia/kbn_circles_vis#2]
why the gulpfile is written in ES6?

It is better to write node version and other useful development  environment.

I add the .babelrc to set preset es2015. Is it right?

**Comment by JuanCarniglia** [comment]
I don't understand the question. How would you rather have it written?

**Comment by JuanCarniglia** [comment]
It is right to add the preset, it was actually there in the first place but I removed it, I know it has to be there due to some bug in Babel right?

**Comment by zuoez02** [comment]
I think it is necessary to add presets for build, add a .babelrc file or add presets in package.json. But if you move the project to KIBANA_HOME/src/plugins and there is a .babelrc or presets in package.json, it will optimize failed.

**Comment by JuanCarniglia** [comment]
I just pushed a new version with some minor changes for this plugin.

Anyway, apart from that, I cloned the project on my src/plugins folder
(Kibana 4.5) and it worked (without installing it).

I am working on some more changes, but as you were having issues using
this, perhaps you can test it?

Thanks

2016-04-07 23:30 GMT-03:00 Luto Yvan notifications@github.com:

> I think it is necessary to add presets for build, add a .babelrc file or
> add presets in package.json. But if you move the project to
> KIBANA_HOME/src/plugins and there is a .babelrc or presets in package.json,
> it will optimize failed.
> 
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> https://github.com/JuanCarniglia/kbn_circles_vis/issues/2#issuecomment-207180649

## 

Juan Ignacio Carniglia

**Comment by sureshamk** [comment]
I too got  build issue 

`
➜  kbn_circles_vis git:(master) ✗ npm run build

> kbn_circles_vis@0.1.0 build /home/suresh/ground/kibana/kbn_circles_vis
> gulp build

[12:17:48] Working directory changed to ~/ground
module.js:341
    throw err;
    ^

Error: Cannot find module 'gulp-util'
    at Function.Module._resolveFilename (module.js:339:15)
    at Function.Module._load (module.js:290:25)
    at Module.require (module.js:367:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/suresh/ground/gulpfile.js:2:13)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)

npm ERR! Linux 3.13.0-96-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "run" "build"
npm ERR! node v5.12.0
npm ERR! npm  v3.8.6
npm ERR! code ELIFECYCLE
npm ERR! kbn_circles_vis@0.1.0 build: `gulp build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the kbn_circles_vis@0.1.0 build script 'gulp build'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the kbn_circles_vis package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     gulp build
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs kbn_circles_vis
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls kbn_circles_vis
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/suresh/ground/kibana/kbn_circles_vis/npm-debug.log
➜  kbn_circles_vis git:(master) ✗ 

`

**Comment by sardetushar** [comment]
same issue .. 
```

17 error Linux 2.6.32-642.13.1.el6.x86_64
18 error argv "/usr/bin/node" "/usr/bin/npm" "run" "build"
19 error node v6.9.5
20 error npm  v3.10.10
21 error code ELIFECYCLE
22 error kbn_circles_vis@0.1.0 build: `gulp build`
22 error Exit status 1
23 error Failed at the kbn_circles_vis@0.1.0 build script 'gulp build'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the kbn_circles_vis package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     gulp build
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs kbn_circles_vis
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls kbn_circles_vis
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]

```
