### ISSUE TITLE
New installed plugin not display in visualization

### ISSUE THREAD

**Issue by mehazkaur** [JuanCarniglia/kbn_circles_vis#3]
i copied kbn_circles_vis into src/plugins. kibana status display kbn_cirlces_vis status ready but this plugin could not display in visualization.

**Comment by JuanCarniglia** [comment]
I don't understand your email.

You should copy it into "_[kibana home]/src/plugins/kbn_circles_vis_".

Remember, that you have to DELETE the "
_[kibana_home]/optimize/bundles/kibana._*" files, in order for V8 to
actually regenerate the big JS and CSS files with all the NEW code.

(It's a good idea to backup those files, before deleting them).

Let me know if it works.

Bye.

2016-05-30 8:41 GMT-03:00 mehazkaur notifications@github.com:

> i copied kbn_circles_vis into src/plugins. kibana status display
> kbn_cirlces_vis status ready but this plugin could not display in
> visualization.
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> https://github.com/JuanCarniglia/kbn_circles_vis/issues/3, or mute the
> thread
> https://github.com/notifications/unsubscribe/AOi0OxG2W7OitXi32Rd-2fnFIKmLPd29ks5qGszogaJpZM4Ipugd
> .

## 

Juan Ignacio Carniglia

**Comment by mehazkaur** [comment]
i copied kbn_circles_vis into src/plugins/.
when i start kibana. it runs in browser properly. when i see its status it display:- 
plugin kbn_circles_vis=ready

but how to use that plugin in visualization.because in visualization we could not find any option for installed plugin. 

As per your suggestion, when i copy  it into "_[kibana home]/src/plugins/kbn_circles_vis_".
delete the _[kibana_home]/optimize/bundles/kibana._*" files, 
kibana did not work.

**Comment by JuanCarniglia** [comment]
You should have something like this (exactly like this actually) in your
Visualizations List:

[image: Imágenes integradas 1]

2016-05-31 5:56 GMT-03:00 mehazkaur notifications@github.com:

> i copied kbn_circles_vis into src/plugins/.
> when i start kibana. it runs on browser properly. when i see its status it
> display:-
> plugin kbn_circles_vis=ready
> 
> but how to use that plugin in visualization.because in visualization we
> could not find any option for installed plugin.
> 
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> https://github.com/JuanCarniglia/kbn_circles_vis/issues/3#issuecomment-222630290,
> or mute the thread
> https://github.com/notifications/unsubscribe/AOi0O8PilO8QHdCuNwmAx6E8I2aUCgj6ks5qG_eigaJpZM4Ipugd
> .

## 

Juan Ignacio Carniglia

**Comment by mehazkaur** [comment]
there is one more problem occured.
when i do the steps that u said  then kibana stop working.after that i copied all kibana.\* files back into optimize/bundles/   directory. but now kibana is loading msg display from the long time. what should i do?

**Comment by JuanCarniglia** [comment]
You could remove the plugin from both the src/plugins and the
installedplugins directory, also removing the kibana.\* Files from the
optimize/bundle folder. That way is like it was before installing anything,
but it would really help me to see some screenshots or error descriptions.

Warning. When you remove the bundled up files, the optimizer creates them
up again and that really can take some time (depends on your hardware, but
around 2 minutes).

**Comment by mehazkaur** [comment]
i removed plugin from src/plugins and installedplugins directory  and also removed files kibana.*. then restart kibana .
out put is:-
![image](https://cloud.githubusercontent.com/assets/16117445/15698155/63af554e-2776-11e6-8da8-a2c785c9a305.png)

**Comment by mehazkaur** [comment]
please tell me complete steps to install plugin into kibana as its new for me.

**Comment by JuanCarniglia** [comment]
First, make Kibana work again. Is kibana running? Have you set it up as a
service? If so run "sudo service kibana status", In any case you can run
"ps aux | grep 'kibana'" to see if it's running.

Once you can get it to run, follow the steps on the github page. They
should work.

**Comment by mehazkaur** [comment]
i checked kibana working or not. so kibana is running.

but when i did the following steps:-
1.git clone https://github.com/JuanCarniglia/kbn_circles_vis.git 
2.cd kbn_circles_vis
3.npm install
4. npm run build
there is an error in npm run build command. 

then i check my kibana working or not.so. its running. 
after that i follow another method:-
1.git clone https://github.com/JuanCarniglia/kbn_circles_vis.git 
          this command make dir kbn_circles_vis.
2.then i copied that directory into src/plugins.

plugin is ready in kibana status but it could not show in visualization list.
what should i do?

**Comment by JuanCarniglia** [comment]
If you add new SOURCE to the SRC folder, you have to tell Node (V8
actually) to regenerate the bundled-up files.

This is done by removing the optimize/bundle/kibana.bundel.js (and CSS if
you changed that too).

Make sure to backup those files before removing them.

After that, restart Kibana, and it will rebuild those files. if everything
goes as planned, you will see the visualization.

2016-06-02 1:15 GMT-03:00 mehazkaur notifications@github.com:

> i checked kibana working or not. so kibana is running.
> 
> but when i did the following steps:-
> 1.git clone https://github.com/JuanCarniglia/kbn_circles_vis.git
> 2.cd kbn_circles_vis
> 3.npm install
> 4. npm run build
> there is an error in npm run build command.
> 
> then i check my kibana working or not.so. its running.
> after that i follow another method:-
> 1.git clone https://github.com/JuanCarniglia/kbn_circles_vis.git
> this command make dir kbn_circles_vis.
> 2.then i copied that directory into src/plugins.
> 
> plugin is ready in kibana status but it could not show in visualization
> list.
> what should i do?
> 
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> https://github.com/JuanCarniglia/kbn_circles_vis/issues/3#issuecomment-223191362,
> or mute the thread
> https://github.com/notifications/unsubscribe/AOi0OxXaro37z3G7XvrvMPkBLId_lUGIks5qHlj2gaJpZM4Ipugd
> .

## 

Juan Ignacio Carniglia

**Comment by JuanCarniglia** [comment]
Any progress?

**Comment by mehazkaur** [comment]
No.

**Comment by mehazkaur** [comment]
Please reply . what should i do?

**Comment by mehazkaur** [comment]
Now i installed kibana 4.5 . its running.but when i 
cp -R kbn_circles_vis /opt/kibana/src/plugins/
and remove kibana.\* files from bundle directory.
kibana is not running.
i checked
cat /var/log/kibana/kibana.stderr.
file contains:-
FATAL [Error: Config schema already has key: kbn_circles_vis]
FATAL [Error: Config schema already has key: kbn_circles_vis]
FATAL [Error: Config schema already has key: kbn_circles_vis]
FATAL [Error: Config schema already has key: kbn_circles_vis]
FATAL [Error: Config schema already has key: kbn_circles_vis]
FATAL [Error: Config schema already has key: kbn_circles_vis]
FATAL [Error: Config schema already has key: kbn_circles_vis]
FATAL { [Error: EACCES: permission denied, open '/opt/kibana/optimize/bundles/kibana.entry.js']
  cause: 
   { [Error: EACCES: permission denied, open '/opt/kibana/optimize/bundles/kibana.entry.js']
     errno: -13,
     code: 'EACCES',
     syscall: 'open',
     path: '/opt/kibana/optimize/bundles/kibana.entry.js' },
  isOperational: true,
  errno: -13,
  code: 'EACCES',
  syscall: 'open',
  path: '/opt/kibana/optimize/bundles/kibana.entry.js' }
FATAL { [Error: EACCES: permission denied, open '/opt/kibana/optimize/bundles/kibana.entry.js']
  cause: 
   { [Error: EACCES: permission denied, open '/opt/kibana/optimize/bundles/kibana.entry.js']
     errno: -13,
     code: 'EACCES',
     syscall: 'open',
     path: '/opt/kibana/optimize/bundles/kibana.entry.js' },
  isOperational: true,
  errno: -13,
  code: 'EACCES',
  syscall: 'open',
  path: '/opt/kibana/optimize/bundles/kibana.entry.js' }
FATAL { [Error: EACCES: permission denied, open '/opt/kibana/optimize/bundles/kibana.entry.js']
  cause: 
   { [Error: EACCES: permission denied, open '/opt/kibana/optimize/bundles/kibana.entry.js']
     errno: -13,
     code: 'EACCES',
     syscall: 'open',
     path: '/opt/kibana/optimize/bundles/kibana.entry.js' },
  isOperational: true,
  errno: -13,
  code: 'EACCES',
  syscall: 'open',
  path: '/opt/kibana/optimize/bundles/kibana.entry.js' }
FATAL { [Error: EACCES: permission denied, open '/opt/kibana/optimize/bundles/kibana.entry.js']
  cause: 
   { [Error: EACCES: permission denied, open '/opt/kibana/optimize/bundles/kibana.entry.js']
     errno: -13,
     code: 'EACCES',
     syscall: 'open',
     path: '/opt/kibana/optimize/bundles/kibana.entry.js' },
  isOperational: true,
  errno: -13,
  code: 'EACCES',
  syscall: 'open',
  path: '/opt/kibana/optimize/bundles/kibana.entry.js' }
FATAL { [Error: EACCES: permission denied, open '/opt/kibana/optimize/bundles/kibana.entry.js']
  cause: 
   { [Error: EACCES: permission denied, open '/opt/kibana/optimize/bundles/kibana.entry.js']
     errno: -13,
     code: 'EACCES',
     syscall: 'open',
     path: '/opt/kibana/optimize/bundles/kibana.entry.js' },
  isOperational: true,
  errno: -13,
  code: 'EACCES',
  syscall: 'open',
  path: '/opt/kibana/optimize/bundles/kibana.entry.js' }
FATAL { [Error: EACCES: permission denied, open '/opt/kibana/optimize/bundles/kibana.entry.js']
  cause: 
   { [Error: EACCES: permission denied, open '/opt/kibana/optimize/bundles/kibana.entry.js']
     errno: -13,
     code: 'EACCES',
     syscall: 'open',
     path: '/opt/kibana/optimize/bundles/kibana.entry.js' },
  isOperational: true,
  errno: -13,
  code: 'EACCES',
  syscall: 'open',
  path: '/opt/kibana/optimize/bundles/kibana.entry.js' }
FATAL { [Error: EACCES: permission denied, open '/opt/kibana/optimize/bundles/kibana.entry.js']
  cause: 
   { [Error: EACCES: permission denied, open '/opt/kibana/optimize/bundles/kibana.entry.js']
     errno: -13,
     code: 'EACCES',
     syscall: 'open',
     path: '/opt/kibana/optimize/bundles/kibana.entry.js' },
  isOperational: true,
  errno: -13,
  code: 'EACCES',
  syscall: 'open',
  path: '/opt/kibana/optimize/bundles/kibana.entry.js' }
FATAL { [Error: EACCES: permission denied, open '/opt/kibana/optimize/bundles/kibana.entry.js']
  cause: 
   { [Error: EACCES: permission denied, open '/opt/kibana/optimize/bundles/kibana.entry.js']
     errno: -13,
     code: 'EACCES',
     syscall: 'open',
     path: '/opt/kibana/optimize/bundles/kibana.entry.js' },
  isOperational: true,
  errno: -13,
  code: 'EACCES',
  syscall: 'open',
  path: '/opt/kibana/optimize/bundles/kibana.entry.js' }
FATAL { [Error: EACCES: permission denied, open '/opt/kibana/optimize/bundles/statusPage.entry.js']
  cause: 
   { [Error: EACCES: permission denied, open '/opt/kibana/optimize/bundles/statusPage.entry.js']
     errno: -13,
     code: 'EACCES',
     syscall: 'open',
     path: '/opt/kibana/optimize/bundles/statusPage.entry.js' },
  isOperational: true,
  errno: -13,
  code: 'EACCES',
  syscall: 'open',
  path: '/opt/kibana/optimize/bundles/statusPage.entry.js' }
FATAL { [Error: EACCES: permission denied, open '/opt/kibana/optimize/bundles/statusPage.entry.js']
  cause: 
   { [Error: EACCES: permission denied, open '/opt/kibana/optimize/bundles/statusPage.entry.js']
     errno: -13,
     code: 'EACCES',
     syscall: 'open',
     path: '/opt/kibana/optimize/bundles/statusPage.entry.js' },
  isOperational: true,
  errno: -13,
  code: 'EACCES',
  syscall: 'open',
  path: '/opt/kibana/optimize/bundles/statusPage.entry.js' }
FATAL { [Error: EACCES: permission denied, open '/opt/kibana/optimize/bundles/commons.bundle.js']
  cause: 
   { [Error: EACCES: permission denied, open '/opt/kibana/optimize/bundles/commons.bundle.js']
     errno: -13,
     code: 'EACCES',
     syscall: 'open',
     path: '/opt/kibana/optimize/bundles/commons.bundle.js' },
  isOperational: true,
  errno: -13,
  code: 'EACCES',
  syscall: 'open',
  path: '/opt/kibana/optimize/bundles/commons.bundle.js' }
FATAL { [Error: EACCES: permission denied, open '/opt/kibana/optimize/bundles/statusPage.entry.js']
  cause: 
   { [Error: EACCES: permission denied, open '/opt/kibana/optimize/bundles/statusPage.entry.js']
     errno: -13,
     code: 'EACCES',
     syscall: 'open',
     path: '/opt/kibana/optimize/bundles/statusPage.entry.js' },
  isOperational: true,
  errno: -13,
  code: 'EACCES',
  syscall: 'open',
  path: '/opt/kibana/optimize/bundles/statusPage.entry.js' }

 where is the problem?

**Comment by JuanCarniglia** [comment]
I just pushed a new version with some minor changes for this plugin.

Anyway, apart from that, I cloned the project on my src/plugins folder
(Kibana 4.5) and it worked (_without installing it_).

I am working on some more changes, but as you were having issues using
this, perhaps you can test it?

Thanks

2016-06-14 2:05 GMT-03:00 mehazkaur notifications@github.com:

> Now i installed kibana 4.5 . its running.but when i
> cp -R kbn_circles_vis /opt/kibana/src/plugins/
> and remove kibana.\* files from bundle directory.
> kibana is not running.
> i checked
> cat /var/log/kibana/kibana.stderr.
> file contains:-
> FATAL [Error: Config schema already has key: kbn_circles_vis]
> FATAL [Error: Config schema already has key: kbn_circles_vis]
> FATAL [Error: Config schema already has key: kbn_circles_vis]
> FATAL [Error: Config schema already has key: kbn_circles_vis]
> FATAL [Error: Config schema already has key: kbn_circles_vis]
> FATAL [Error: Config schema already has key: kbn_circles_vis]
> FATAL [Error: Config schema already has key: kbn_circles_vis]
> FATAL { [Error: EACCES: permission denied, open
> '/opt/kibana/optimize/bundles/kibana.entry.js']
> cause:
> { [Error: EACCES: permission denied, open
> '/opt/kibana/optimize/bundles/kibana.entry.js']
> errno: -13,
> code: 'EACCES',
> syscall: 'open',
> path: '/opt/kibana/optimize/bundles/kibana.entry.js' },
> isOperational: true,
> errno: -13,
> code: 'EACCES',
> syscall: 'open',
> path: '/opt/kibana/optimize/bundles/kibana.entry.js' }
> FATAL { [Error: EACCES: permission denied, open
> '/opt/kibana/optimize/bundles/kibana.entry.js']
> cause:
> { [Error: EACCES: permission denied, open
> '/opt/kibana/optimize/bundles/kibana.entry.js']
> errno: -13,
> code: 'EACCES',
> syscall: 'open',
> path: '/opt/kibana/optimize/bundles/kibana.entry.js' },
> isOperational: true,
> errno: -13,
> code: 'EACCES',
> syscall: 'open',
> path: '/opt/kibana/optimize/bundles/kibana.entry.js' }
> FATAL { [Error: EACCES: permission denied, open
> '/opt/kibana/optimize/bundles/kibana.entry.js']
> cause:
> { [Error: EACCES: permission denied, open
> '/opt/kibana/optimize/bundles/kibana.entry.js']
> errno: -13,
> code: 'EACCES',
> syscall: 'open',
> path: '/opt/kibana/optimize/bundles/kibana.entry.js' },
> isOperational: true,
> errno: -13,
> code: 'EACCES',
> syscall: 'open',
> path: '/opt/kibana/optimize/bundles/kibana.entry.js' }
> FATAL { [Error: EACCES: permission denied, open
> '/opt/kibana/optimize/bundles/kibana.entry.js']
> cause:
> { [Error: EACCES: permission denied, open
> '/opt/kibana/optimize/bundles/kibana.entry.js']
> errno: -13,
> code: 'EACCES',
> syscall: 'open',
> path: '/opt/kibana/optimize/bundles/kibana.entry.js' },
> isOperational: true,
> errno: -13,
> code: 'EACCES',
> syscall: 'open',
> path: '/opt/kibana/optimize/bundles/kibana.entry.js' }
> FATAL { [Error: EACCES: permission denied, open
> '/opt/kibana/optimize/bundles/kibana.entry.js']
> cause:
> { [Error: EACCES: permission denied, open
> '/opt/kibana/optimize/bundles/kibana.entry.js']
> errno: -13,
> code: 'EACCES',
> syscall: 'open',
> path: '/opt/kibana/optimize/bundles/kibana.entry.js' },
> isOperational: true,
> errno: -13,
> code: 'EACCES',
> syscall: 'open',
> path: '/opt/kibana/optimize/bundles/kibana.entry.js' }
> FATAL { [Error: EACCES: permission denied, open
> '/opt/kibana/optimize/bundles/kibana.entry.js']
> cause:
> { [Error: EACCES: permission denied, open
> '/opt/kibana/optimize/bundles/kibana.entry.js']
> errno: -13,
> code: 'EACCES',
> syscall: 'open',
> path: '/opt/kibana/optimize/bundles/kibana.entry.js' },
> isOperational: true,
> errno: -13,
> code: 'EACCES',
> syscall: 'open',
> path: '/opt/kibana/optimize/bundles/kibana.entry.js' }
> FATAL { [Error: EACCES: permission denied, open
> '/opt/kibana/optimize/bundles/kibana.entry.js']
> cause:
> { [Error: EACCES: permission denied, open
> '/opt/kibana/optimize/bundles/kibana.entry.js']
> errno: -13,
> code: 'EACCES',
> syscall: 'open',
> path: '/opt/kibana/optimize/bundles/kibana.entry.js' },
> isOperational: true,
> errno: -13,
> code: 'EACCES',
> syscall: 'open',
> path: '/opt/kibana/optimize/bundles/kibana.entry.js' }
> FATAL { [Error: EACCES: permission denied, open
> '/opt/kibana/optimize/bundles/kibana.entry.js']
> cause:
> { [Error: EACCES: permission denied, open
> '/opt/kibana/optimize/bundles/kibana.entry.js']
> errno: -13,
> code: 'EACCES',
> syscall: 'open',
> path: '/opt/kibana/optimize/bundles/kibana.entry.js' },
> isOperational: true,
> errno: -13,
> code: 'EACCES',
> syscall: 'open',
> path: '/opt/kibana/optimize/bundles/kibana.entry.js' }
> FATAL { [Error: EACCES: permission denied, open
> '/opt/kibana/optimize/bundles/statusPage.entry.js']
> cause:
> { [Error: EACCES: permission denied, open
> '/opt/kibana/optimize/bundles/statusPage.entry.js']
> errno: -13,
> code: 'EACCES',
> syscall: 'open',
> path: '/opt/kibana/optimize/bundles/statusPage.entry.js' },
> isOperational: true,
> errno: -13,
> code: 'EACCES',
> syscall: 'open',
> path: '/opt/kibana/optimize/bundles/statusPage.entry.js' }
> FATAL { [Error: EACCES: permission denied, open
> '/opt/kibana/optimize/bundles/statusPage.entry.js']
> cause:
> { [Error: EACCES: permission denied, open
> '/opt/kibana/optimize/bundles/statusPage.entry.js']
> errno: -13,
> code: 'EACCES',
> syscall: 'open',
> path: '/opt/kibana/optimize/bundles/statusPage.entry.js' },
> isOperational: true,
> errno: -13,
> code: 'EACCES',
> syscall: 'open',
> path: '/opt/kibana/optimize/bundles/statusPage.entry.js' }
> FATAL { [Error: EACCES: permission denied, open
> '/opt/kibana/optimize/bundles/commons.bundle.js']
> cause:
> { [Error: EACCES: permission denied, open
> '/opt/kibana/optimize/bundles/commons.bundle.js']
> errno: -13,
> code: 'EACCES',
> syscall: 'open',
> path: '/opt/kibana/optimize/bundles/commons.bundle.js' },
> isOperational: true,
> errno: -13,
> code: 'EACCES',
> syscall: 'open',
> path: '/opt/kibana/optimize/bundles/commons.bundle.js' }
> FATAL { [Error: EACCES: permission denied, open
> '/opt/kibana/optimize/bundles/statusPage.entry.js']
> cause:
> { [Error: EACCES: permission denied, open
> '/opt/kibana/optimize/bundles/statusPage.entry.js']
> errno: -13,
> code: 'EACCES',
> syscall: 'open',
> path: '/opt/kibana/optimize/bundles/statusPage.entry.js' },
> isOperational: true,
> errno: -13,
> code: 'EACCES',
> syscall: 'open',
> path: '/opt/kibana/optimize/bundles/statusPage.entry.js' }
> 
> where is the problem?
> 
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> https://github.com/JuanCarniglia/kbn_circles_vis/issues/3#issuecomment-225780871,
> or mute the thread
> https://github.com/notifications/unsubscribe/AOi0Oz-U15sGZcm901aeE2kTn0HlnWTbks5qLjaggaJpZM4Ipugd
> .

## 

Juan Ignacio Carniglia
